### ISSUE TITLE
Item creation (Not finished, i finish later)

### ISSUE THREAD

**Issue by TokkyCzech** [NosWings/wiki#4]
# How to create an item

### How item creation command looks

How item creation command looks • `$item 5060 1`
How equipment creation command looks  • `$item 4903 1 8 10`
How sp creation command looks  • `$sp 912 15`

### What this numbers means?
In case of creating an item it mean • `[Command] [Vnum] [Quantity]`
In case of creating a equipment it mean •`[Command] [Vnum] [Quantity] [Rarity] [Upgrade]`
In case of creating SP card it mean  • `[Command] [Vnum] [Upgrade]`

### What is 'Vnum'?
Vnum is basically number or ID with which you can create items

### Where i find all Vnum's of items?
[Simply go on this website](https://friends111.nostale.club/list/items.php?l=uk)

### Here is commands for champion equipment c45/c48 you can copy paste in chat
*Swordsman*
`$item 4981 1 8 10` • Broken Krem’s Right Blade r8+10
`$item 4978 1 8 10` • Luminiel’s Shining Crossbow r8+10
`$item 4984 1 8 10` • Brave Shares‘ Heavy Armour r8+10

*Archer*
`$item 4983 1 8 10` • Azrael’s Wings r8+10
`$item 4980 1 8 10` • Broken Krem's Left Blade r8+10
`$item 4986 1 8 10` • Leather Armour of Silver Soul Glacernon r8+10

*Mage*
`$item 4982 1 8 10` • Seli-Lusha's Branch of Light r8+10
`$item 4979 1 8 10` • Abyssal Lorten's Spell Gun r8+10
`$item 4985 1 8 10` • Mukraju's Robe r8+10

*Martial artist*
`$item 4736 1 8 10`  • Divine Fist r8+10
`$item 4770 1 8 10`  • Magic Black Turtle Token
`$item 4754 1 8 10`  • Champion's Armour r8+10

**Comment by Kravos** [comment]
Please use markdown 

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
